package com.qmentis.pojos;

/**
 * LoginRequest - POJO class for login request payload
 * Auto-generated by QMentis Test Automation Agent
 */

public class LoginRequest {
    
    // Fields corresponding to the JSON template
    private String username;
    private String password;
    private String deviceId;
    
    // Default constructor
    public LoginRequest() {}
    
    // Parameterized constructor
    public LoginRequest(String username, String password, String deviceId) {
        this.username = username;
        this.password = password;
        this.deviceId = deviceId;
    }
    
    // Getter and Setter for username
    public String getUsername() {
        return username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    // Getter and Setter for password
    public String getPassword() {
        return password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    // Getter and Setter for deviceId
    public String getDeviceId() {
        return deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    
    // Overriding toString for better logging
    @Override
    public String toString() {
        return "LoginRequest{" +
                "username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", deviceId='" + deviceId + '\'' +
                '}';
    }
}