package com.qmentis.pojos;

/**
 * LoginResponse - POJO for capturing login API response details
 * Auto-generated by QMentis Test Automation Agent
 */

public class LoginResponse {
    
    private String token;
    private String message;

    // Default constructor
    public LoginResponse() {}

    // Parameterized constructor
    public LoginResponse(String token, String message) {
        this.token = token;
        this.message = message;
    }

    // Getter for token
    public String getToken() {
        return token;
    }

    // Setter for token
    public void setToken(String token) {
        this.token = token;
    }

    // Getter for message
    public String getMessage() {
        return message;
    }

    // Setter for message
    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public String toString() {
        return "LoginResponse{" +
                "token='" + token + '\'' +
                ", message='" + message + '\'' +
                '}';
    }
}