package com.qmentis.api_tests;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.testng.annotations.*;
import org.testng.asserts.SoftAssert;
import static org.hamcrest.Matchers.*;
import static io.restassured.RestAssured.given;

import com.qmentis.pojos.LoginRequest;
import com.qmentis.pojos.LoginResponse;
import com.qmentis.base.BaseRestAssuredTest;

/**
 * TestLoginAPI - TestNG test class for /login API
 * Auto-generated by QMentis Test Automation Agent
 * 
 * Test Case: Test login API with valid credentials and invalid credentials
 */
public class TestLoginAPI extends BaseRestAssuredTest {
    
    private static final String ENDPOINT = "/login";
    private RequestSpecification request;
    
    @BeforeClass
    public void setUp() {
        RestAssured.baseURI = config.getBaseUrl();
        RestAssured.basePath = "/api/v1";
        request = given()
            .header("Content-Type", "application/json")
            .header("Accept", "application/json");
    }
    
    /**
     * Data provider for login test scenarios
     */
    @DataProvider(name = "loginData")
    public Object[][] loginDataProvider() {
        return new Object[][] {
            {"Valid credentials", "testuser@example.com", "ValidPass123!", "android_test_001"},
            {"Invalid credentials", "invaliduser@example.com", "WrongPass!", "android_test_002"}
        };
    }
    
    /**
     * Test Case: Test login API with valid credentials
     * Expected: Status 200, token present
     */
    @Test(groups = {"api", "smoke"}, dataProvider = "loginData", priority = 1)
    public void testValidLogin(String scenario, String username, String password, String deviceId) {
        if ("Valid credentials".equals(scenario)) {
            // Arrange
            LoginRequest requestBody = LoginRequest.builder()
                .username(username)
                .password(password)
                .deviceId(deviceId)
                .build();
            
            // Act
            Response response = request
                .body(requestBody)
                .post(ENDPOINT);
            
            // Assert
            SoftAssert softly = new SoftAssert();
            softly.assertEquals(response.getStatusCode(), 200, "Status code mismatch");
            
            LoginResponse responseBody = response.as(LoginResponse.class);
            softly.assertNotNull(responseBody.getToken(), "Token should not be null");
            softly.assertTrue(responseBody.getMessage().contains("success"), "Message should contain 'success'");
            
            softly.assertAll();
        }
    }
    
    /**
     * Test Case: Test login API with invalid credentials
     * Expected: Status 401, error message
     */
    @Test(groups = {"api", "negative"}, priority = 2)
    public void testInvalidLogin() {
        // Arrange
        LoginRequest requestBody = LoginRequest.builder()
            .username("invaliduser@example.com")
            .password("WrongPass!")
            .deviceId("android_test_002")
            .build();
        
        // Act
        Response response = request
            .body(requestBody)
            .post(ENDPOINT);
        
        // Assert
        response.then()
            .statusCode(401)
            .body("errors[0].message", containsString("Invalid credentials"));
    }
    
    @AfterClass
    public void tearDown() {
        // Cleanup if needed
    }
}